force-mdapi/objects/Events_Generator__mdt.object
<CustomObject>
    <label>Events Generator</label>
    <pluralLabel>Events Generators</pluralLabel>
    <fields>
        <fullName>Event_Data__c</fullName>
        <label>Event Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-mdapi/classes/GenerateEventController.cls
public class GenerateEventController {
    @AuraEnabled
    public static void publishEvent(SObject newEvent) {
        publishEvents(newEvent);
    }
    
    public static List<Database.SaveResult> publishEvents(SObject newEvent) {
        List<SObject> events = new List<SObject>();
        events.add(newEvent);
        
        List<Database.SaveResult> results = EventBus.publish(events);
        return results;
    }
    
    @AuraEnabled
    public static List<Events_Generator__mdt> listMetadata(String grouping) {
        List<Events_Generator__mdt> results = [SELECT Id, Label, DeveloperName, Event_Data__c
                                               FROM Events_Generator__mdt
                                               WHERE Group__c = :grouping
                                               ORDER BY Label];
        return results;
    }
    
    @AuraEnabled
    public static Events_Generator__mdt selectMetadata(String devName) {
        List<Events_Generator__mdt> results = [SELECT Id, Label, DeveloperName, Event_Data__c
                                               FROM Events_Generator__mdt
                                               WHERE DeveloperName = :devName];
        return results[0];
    }
}