force-mdapi/objects/Events_Generator__mdt.object
<CustomObject>
    <label>Events Generator</label>
    <pluralLabel>Events Generators</pluralLabel>
</CustomObject>

force-mdapi/objects/Log__e.object
<CustomObject>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/GenerateEventControllerTest.cls
@isTest
private class GenerateEventControllerTest {
    @isTest static void testListMetadata() {
        Test.startTest();
        
        //be warned, MDT are always visible to testing
        List<Events_Generator__mdt> l = GenerateEventController.listMetadata('Stage');
        
        System.assert(l.size() > 0);
        
        Test.stopTest();
    }

    @isTest static void testSelectMetadata() {
        Test.startTest();
        
        Events_Generator__mdt i = GenerateEventController.selectMetadata('Stage_One');
        
        System.assert(i <> null);
        
        Test.stopTest();
    }

    @isTest static void testPublishEvent() {
        Log__e i = new Log__e(Message__c = 'Hello');

        Test.startTest();
        
        // add code coverage
		GenerateEventController.publishEvent(i);
        List<Database.SaveResult> srs = GenerateEventController.publishEvents(i);
        
        Test.stopTest();
        
        System.assert(i <> null);
        
        for (Database.SaveResult sr : srs) {
        	System.assertEquals(true, sr.isSuccess());
        }
    }
}